### ISSUE TITLE
instance of class is being update.

### ISSUE THREAD

**Issue by jmvtrinidad** [variotry/knockout-decorator#1]
I have a list of Person.

```
export class Person {
    @kd.observable
    name: string;
}
```

Every time I update name, the value of other list will be the same.
When I looked into JavaScript code it gets being a prototype of that instance.
Any workaround for this?

**Comment by variotry** [comment]
Thank you for the report.
I have fixed the bug and pushed to development branch.
Would you please check the fix?

**Comment by jmvtrinidad** [comment]
It works for me. Thanks.
Can you explain what changes for this update?

Maybe this plugins will help you for future updates like decorators in class level.
- [ko-es5](http://blog.stevensanderson.com/2013/05/20/knockout-es5-a-plugin-to-simplify-your-syntax/)
- [ko-es5-option4](https://github.com/nathanboktae/knockout-es5-option4)

**Comment by variotry** [comment]
Thank you for cheking.

> Can you explain what changes for this update?

Please excuse me if you may not understand since I am bad at writing English.

Point of changes create observable objects and is to use it for each instance properties.
Flow of processing is following.
1. When you first access a property, a prototype accessor defined in decorator process is executed.
2. My plugin defines accessor for the instance inside the prototype accessor.
   （A instance can be obtained using `this` inside a prototype accessor.）
3. My plugin creates observable object and associates the instance property with it inside the accessor.
4. In each access the property after the first, the accessor defined within instance is executed and the observable object associated is used.(The prototype accessor is no longer executed.) Thus the observable object is not interfere with other instance objects.

**Comment by jmvtrinidad** [comment]
Awesome work. Thanks
